In [1]:
import pandas as pd

df = pd.read_csv('savant_pitch_2024.csv')
df

,pitches,player_id,player_name,total_pitches,pitch_percent,ba,iso,babip,slg,woba,...,xslgdiff,wobadiff,swing_miss_percent,arm_angle,attack_angle,attack_direction,swing_path_tilt,rate_ideal_attack_angle,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
0,3201,657277,"Webb, Logan",3201,100,0.258,0.097,0.316,0.355,0.288,...,-0.057,-0.032,20.8,22.1,6.310522,3.344084,34.776278,0.465530,37.042447,28.076034
1,3189,605400,"Nola, Aaron",3189,100,0.248,0.174,0.294,0.422,0.310,...,0.034,0.010,25.2,20.1,11.926067,-5.505028,33.250844,0.540301,37.485770,33.226783
2,3188,656302,"Cease, Dylan",3188,100,0.200,0.132,0.266,0.332,0.266,...,-0.026,-0.017,32.4,53.4,10.374077,-2.067445,31.384221,0.521739,37.953553,30.809408
3,3134,554430,"Wheeler, Zack",3134,100,0.192,0.136,0.247,0.328,0.256,...,0.000,-0.005,27.5,24.7,7.282499,2.912895,32.199553,0.471686,35.840768,27.314152
4,3118,666142,"Ragans, Cole",3118,100,0.213,0.121,0.292,0.334,0.277,...,-0.006,-0.006,32.0,45.1,10.459098,-3.811388,32.360346,0.452937,37.602776,31.271803
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
850,5,640902,"Pereda, Jhonny",5,100,0.000,0.000,0.000,0.000,0.000,...,-0.891,-0.719,0.0,46.8,17.639566,-22.645116,29.424474,1.000000,34.739708,43.967848
851,4,667478,"Kravetz, Evan",4,100,0.000,0.000,0.000,0.000,0.000,...,-0.243,-0.204,0.0,48.9,6.416036,-4.277619,31.642524,1.000000,37.424294,30.868656
852,3,620443,"Torrens, Luis",3,100,0.000,0.000,0.000,0.000,0.000,...,-0.232,-0.209,0.0,60.7,NaN,NaN,NaN,NaN,NaN,NaN
853,3,593934,"San√≥, Miguel",3,100,0.000,0.000,0.000,0.000,0.000,...,-0.049,-0.064,33.3,23.7,-2.176088,22.016898,23.152914,0.000000,39.474724,21.129739
854,2,593833,"Suero, Wander",2,100,1.000,0.000,1.000,1.000,0.882,...,-0.517,-0.050,0.0,39.7,13.804714,-9.636341,29.455242,1.000000,44.205575,34.761650

In [2]:
columns_to_keep = [
    "player_id", "player_name", "xwoba", "k_percent", "bb_percent",
    "hardhit_percent", "barrels_per_bbe_percent", "velocity", "spin_rate", "swing_miss_percent"
]
df_filtered = df[columns_to_keep]
df_filtered

,player_id,player_name,xwoba,k_percent,bb_percent,hardhit_percent,barrels_per_bbe_percent,velocity,spin_rate,swing_miss_percent
0,657277,"Webb, Logan",0.320,20.5,5.6,46.191248,6.969206,89.0,1947,20.8
1,605400,"Nola, Aaron",0.300,23.9,6.1,38.245614,7.192982,86.8,2317,25.2
2,656302,"Cease, Dylan",0.283,29.4,8.5,38.592751,8.528785,90.9,2672,32.4
3,554430,"Wheeler, Zack",0.261,28.5,6.6,33.598410,8.349901,91.4,2392,27.5
4,666142,"Ragans, Cole",0.283,29.3,8.7,35.407725,6.223176,89.6,2445,32.0
...,...,...,...,...,...,...,...,...,...,...
850,640902,"Pereda, Jhonny",0.719,0.0,0.0,100.000000,0.000000,56.1,1278,0.0
851,667478,"Kravetz, Evan",0.204,0.0,0.0,50.000000,0.000000,85.1,1948,0.0
852,620443,"Torrens, Luis",0.209,0.0,0.0,100.000000,0.000000,60.7,1515,0.0
853,593934,"San√≥, Miguel",0.064,0.0,0.0,0.000000,0.000000,79.1,1879,33.3
854,593833,"Suero, Wander",0.932,0.0,0.0,100.000000,100.000000,89.8,2540,0.0

In [3]:
df_filtered.to_csv('pitch_cleaned.csv', index=False)

In [4]:
import pandas as pd

df1 = pd.read_csv('savant_bat_2024.csv')
df2 = pd.read_csv('savant_bat_2024_2.csv')
df = pd.concat([df1, df2], ignore_index=True)
df

,pitches,player_id,player_name,total_pitches,pitch_percent,ba,iso,babip,slg,woba,...,xslgdiff,wobadiff,swing_miss_percent,arm_angle,attack_angle,attack_direction,swing_path_tilt,rate_ideal_attack_angle,intercept_ball_minus_batter_pos_x_inches,intercept_ball_minus_batter_pos_y_inches
0,2960,665742,"Soto, Juan",2960,100.0,0.289,0.282,0.298,0.570,0.421,...,-0.077,-0.042,21.5,37.8,11.474623,3.962532,27.101748,0.590775,39.331170,25.049922
1,2896,683002,"Henderson, Gunnar",2896,100.0,0.281,0.248,0.320,0.529,0.381,...,0.037,0.008,24.4,37.8,7.693294,4.215383,30.487502,0.454768,35.248052,31.899643
2,2885,592450,"Judge, Aaron",2885,100.0,0.322,0.379,0.367,0.701,0.476,...,-0.022,-0.003,30.7,38.5,13.800692,-3.749367,39.734243,0.494585,42.607381,29.375944
3,2844,680776,"Duran, Jarren",2844,100.0,0.285,0.207,0.345,0.492,0.357,...,0.044,0.019,24.8,38.1,3.176290,4.160979,29.192553,0.345267,39.224007,26.621179
4,2821,650402,"Torres, Gleyber",2821,100.0,0.257,0.121,0.306,0.378,0.313,...,0.010,0.006,22.9,38.6,7.607850,6.306425,34.538327,0.506266,36.377728,29.964198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
683,11,676946,"Batten, Matthew",11,100.0,0.333,0.667,0.333,1.000,0.530,...,0.651,0.275,25.0,31.8,3.575678,5.091981,21.882495,0.500000,38.944634,26.529715
684,10,670869,"Soto, Livan",66,15.2,0.000,0.000,0.000,0.000,0.000,...,-0.013,-0.009,20.0,27.6,16.432138,-1.976688,42.027861,0.400000,31.405156,30.464049
685,7,687066,"Yang, Eric",7,100.0,0.000,0.000,NaN,0.000,0.000,...,NaN,0.000,75.0,47.6,2.784801,9.183666,26.466934,0.250000,38.401206,25.998908
686,6,676896,"Roller, Chris",6,100.0,0.000,0.000,NaN,0.000,0.000,...,NaN,0.000,40.0,27.0,17.722556,-7.749157,36.672021,0.500000,35.995546,29.616098
687,4,543518,"McGough, Scott",4,100.0,0.000,0.000,NaN,0.000,0.000,...,NaN,0.000,0.0,36.6,-16.680760,50.516878,26.513673,0.000000,36.897970,-0.869785

In [5]:
columns_selected = [
    "player_id", "player_name", "xwoba", "k_percent", "bb_percent",
    "barrels_per_pa_percent", "hardhit_percent", "launch_speed", "bat_speed"
]
df_selected = df[columns_selected]
df_selected

,player_id,player_name,xwoba,k_percent,bb_percent,barrels_per_pa_percent,hardhit_percent,launch_speed,bat_speed
0,665742,"Soto, Juan",0.463,16.6,17.9,12.816901,56.832972,93.5,72.9
1,683002,"Henderson, Gunnar",0.373,22.2,10.5,7.402235,53.894737,92.8,74.7
2,592450,"Judge, Aaron",0.479,25.0,16.5,15.350877,61.025641,96.2,75.7
3,680776,"Duran, Jarren",0.338,21.8,7.2,6.539510,43.883495,90.2,71.8
4,650402,"Torres, Gleyber",0.307,20.5,9.8,4.360902,35.357918,88.2,68.4
...,...,...,...,...,...,...,...,...,...
683,676946,"Batten, Matthew",0.255,0.0,0.0,0.000000,33.333333,85.6,68.4
684,670869,"Soto, Livan",0.009,33.3,0.0,0.000000,50.000000,90.2,68.0
685,687066,"Yang, Eric",0.000,100.0,0.0,0.000000,NaN,NaN,65.6
686,676896,"Roller, Chris",0.000,100.0,0.0,0.000000,NaN,NaN,67.5
687,543518,"McGough, Scott",0.000,100.0,0.0,0.000000,NaN,NaN,56.7

In [6]:
df_selected.to_csv('bat_cleaned.csv', index=False)